name: Check Abonoteatro cada 10 min

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v3

      - name: Ejecutar Scraper PowerShell
        shell: pwsh
        run: |
          ./script.ps1
        env:
          ABONO_USER: ${{ secrets.ABONO_USER }}
          ABONO_PASS: ${{ secrets.ABONO_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          URL_BASE: ${{ secrets.URL_BASE }}
          URL_DETALLE: ${{ secrets.URL_DETALLE }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_TEATRO: ${{ secrets.URL_TEATRO }}
          URL_REFERER: ${{ secrets.URL_REFERER }}

      - name: Guardar cambios en los ficheros (Persistencia)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add eventos_anteriores.csv Data.txt envios.csv
          git commit -m "Auto-update: $(Get-Date -Format 'yyyy-MM-dd HH:mm')" || exit 0
          git push
