name: Check Abonoteatro cada 10 min

on:
  workflow_dispatch:
  repository_dispatch:
    types: [lanzar_script]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar Scraper PowerShell
        shell: pwsh
        run: |
          ./ScheduleScript.ps1
        env:
          ABONO_USER: ${{ secrets.ABONO_USER }}
          ABONO_PASS: ${{ secrets.ABONO_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          URL_BASE: ${{ secrets.URL_BASE }}
          URL_DETALLE: ${{ secrets.URL_DETALLE }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_TEATRO: ${{ secrets.URL_TEATRO }}
          URL_REFERER: ${{ secrets.URL_REFERER }}

      - name: Guardar cambios en los ficheros (Persistencia)
        shell: pwsh
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 1. Añadimos los archivos específicos y cualquier transcripción que empiece por "transcripcion_"
          # Usamos un try/catch o simplemente añadimos lo que exista
          git add eventos_anteriores.csv Data.txt
          git add transcripcion_*.txt
          
          # 2. Comprobamos si hay algo nuevo en el área de preparación (staging)
          $status = git status --porcelain
          if ($status) {
              Write-Host "Se han detectado cambios. Guardando en GitHub..."
              git commit -m "Auto-update y Log: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
              git push
          } else {
              Write-Host "No hay cambios para subir."
          }
