name: Check Abonoteatro cada 2 min

on:
  workflow_dispatch:
  repository_dispatch:
    types: [lanzar_script]
  schedule:
    - cron: '*/10 * * * *'  # Intenta lanzarse cada 10 minutos

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false   # CLAVE: Evita que el nuevo cancele al que lleva 2h corriendo

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Ejecutar Scraper PowerShell
        shell: pwsh
        run: |
          ./ScheduleScriptsupercharger.ps1
        env:
          ABONO_USER: ${{ secrets.ABONO_USER }}
          ABONO_PASS: ${{ secrets.ABONO_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          URL_BASE: ${{ secrets.URL_BASE }}
          URL_DETALLE: ${{ secrets.URL_DETALLE }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_TEATRO: ${{ secrets.URL_TEATRO }}
          URL_REFERER: ${{ secrets.URL_REFERER }}

      - name: Guardar cambios en los ficheros (Persistencia)
        if: always()
        shell: pwsh
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add -A
          
          $status = git status --porcelain
          if ($status) {
              Write-Host "Sincronizando CSV, txt y logs finales con GitHub..."
              git commit -m "Auto-cleanup y log final: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
              git push
          } else {
              Write-Host "Sin cambios relevantes al finalizar."
          }
